### ISSUE TITLE
Datashader Crashes Kernel on import

### ISSUE THREAD

**Issue by rjgiedt** [holoviz/datashader#912] opened 2020-05-06 01:34 UTC
Hi, I just installed datashader hoping to use it, but it crashes my kernel when I try to import it both in a notebook and from the terminal. In the terminal I get the following message: 

"Assertion failed: (PassInf && "Expected all immutable passes to be initialized"), function addImmutablePass, file /opt/concourse/worker/volumes/live/beb14cc7-dab9-473f-6096-a3a28d4f005a/volume/llvmdev_1526578337017/work/lib/IR/LegacyPassManager.cpp, line 755.
Abort trap: 6
"

Software versions are: 

Python 3.6.5
absl-py                            0.2.2       
aiohttp                            3.6.2       
alabaster                          0.7.10      
amqp                               2.3.2       
anaconda-client                    1.6.14      
anaconda-navigator                 1.9.2       
anaconda-project                   0.8.2       
apeer-ometiff-library              1.6.0       
appnope                            0.1.0       
appscript                          1.0.1       
asgiref                            1.1.2       
asn1crypto                         0.24.0      
astor                              0.7.1       
astroid                            1.6.3       
astropy                            3.0.2       
async-timeout                      3.0.1       
attrs                              18.1.0      
autobahn                           18.6.1      
Automat                            0.7.0       
Babel                              2.5.3       
backcall                           0.1.0       
backports.functools-lru-cache      1.6.1       
backports.shutil-get-terminal-size 1.0.0       
backports.tempfile                 1.0         
backports.weakref                  1.0.post1   
bcrypt                             3.1.4       
beautifulsoup4                     4.6.0       
billiard                           3.5.0.4     
bitarray                           0.8.1       
bkcharts                           0.2         
blaze                              0.11.3      
bleach                             2.1.3       
bokeh                              0.12.16     
boto                               2.48.0      
boto3                              1.7.58      
botocore                           1.10.58     
Bottleneck                         1.2.1       
cachetools                         2.1.0       
celery                             4.2.0       
certifi                            2018.4.16   
cffi                               1.11.5      
channels                           1.1.8       
chardet                            3.0.4       
cheroot                            6.3.3       
CherryPy                           11.0.0      
click                              6.7         
click-plugins                      1.0.3       
cloudpickle                        0.5.3       
clyent                             1.2.2       
cmake                              3.11.0      
colorama                           0.3.9       
colorcet                           2.0.2       
conda                              4.8.3       
conda-build                        3.10.5      
conda-package-handling             1.6.0       
conda-verify                       3.4.2       
constantly                         15.1.0      
contextlib2                        0.5.5       
cryptography                       2.2.2       
cycler                             0.10.0      
Cython                             0.29.15     
cytoolz                            0.9.0.1     
czifile                            2019.7.2    
daphne                             1.4.2       
dask                               2.9.2       
datashader                         0.6.9       
datashape                          0.5.4       
decorator                          4.3.0       
diskcache                          3.0.6       
distributed                        1.21.8      
Django                             1.10.8      
djangorestframework                3.4.7       
docker                             3.4.1       
docker-pycreds                     0.3.0       
docutils                           0.14        
dogpile.cache                      0.6.6       
entrypoints                        0.2.3       
enum34                             1.1.6       
et-xmlfile                         1.0.1       
fastcache                          1.0.2       
feather-format                     0.4.0       
filelock                           3.0.4       
Flask                              1.0.2       
Flask-Cors                         3.0.4       
freetype-py                        2.1.0.post1 
fsspec                             0.6.2       
future                             0.18.2      
gast                               0.2.0       
gevent                             1.3.0       
girder                             2.5.0       
girder-client                      2.4.0       
girder-worker                      0.5.0       
girder-worker-utils                0.8.3       
glob2                              0.6         
gmpy2                              2.0.8       
google                             2.0.3       
greenlet                           0.4.13      
grpcio                             1.13.0      
h5py                               2.7.1       
hdbscan                            0.8.24      
hdf5storage                        0.1.14      
heapdict                           1.0.0       
histomicstk                        0.2.0       /Users/giedtji1/HistomicsTK
html5lib                           1.0.1       
htmlmin                            0.1.12      
hyperlink                          18.0.0      
idna                               2.6         
idna-ssl                           1.1.0       
imagecodecs-lite                   2019.12.3   
imageio                            2.3.0       
imagesize                          1.0.0       
imbalanced-learn                   0.3.3       
img-utils                          0.0.13      
imglyb                             0.4.0       
importlib-metadata                 0.23        
imutils                            0.5.3       
incremental                        17.5.0      
ipykernel                          5.1.3       
ipython                            7.11.1      
ipython-genutils                   0.2.0       
ipywidgets                         7.2.1       
isort                              4.3.4       
itsdangerous                       0.24        
jaraco.functools                   1.20        
jdcal                              1.4         
jedi                               0.12.0      
jgo                                0.5.0       
Jinja2                             2.10        
jmespath                           0.9.3       
joblib                             0.14.1      
jsonfield                          2.0.2       
jsonpickle                         0.9.6       
jsonschema                         2.6.0       
jupyter                            1.0.0       
jupyter-client                     5.2.3       
jupyter-console                    5.2.0       
jupyter-core                       4.4.0       
jupyterlab                         0.32.1      
jupyterlab-launcher                0.10.5      
Keras                              2.2.0       
Keras-Applications                 1.0.2       
Keras-Preprocessing                1.0.1       
kiwisolver                         1.0.1       
kombu                              4.2.1       
large-image                        0.3.0       /Users/giedtji1/large_image
lazy-object-proxy                  1.3.1       
libtiff                            0.4.2       
lifelines                          0.17.0      
lime                               0.1.1.32    
llvmlite                           0.23.1      
lmdb                               0.94        
locket                             0.2.0       
lxml                               4.2.1       
Mako                               1.0.7       
Markdown                           2.6.11      
MarkupSafe                         1.0         
matplotlib                         2.2.2       
mccabe                             0.6.1       
missingno                          0.4.2       
mistune                            0.8.3       
mkl-fft                            1.0.0       
mkl-random                         1.0.1       
more-itertools                     4.1.0       
mpmath                             1.0.0       
mrcnn                              0.2         
msgpack                            0.5.6       
msgpack-python                     0.5.6       
multidict                          4.7.5       
multipledispatch                   0.5.0       
mypy-extensions                    0.3.0       
navigator-updater                  0.2.1       
nb-conda                           2.2.1       
nb-conda-kernels                   2.2.3       
nbconvert                          5.3.1       
nbformat                           4.4.0       
networkx                           1.11        
nimfa                              1.3.4       
nltk                               3.3         
nose                               1.3.7       
notebook                           5.5.0       
numba                              0.38.0      
numexpr                            2.6.5       
numpy                              1.16.0      
numpydoc                           0.9.2       
odo                                0.5.1       
olefile                            0.45.1      
opencv-contrib-python              4.0.0.21    
opencv-python                      3.4.1.15    
openpyxl                           2.5.3       
openslide-python                   1.1.1       
openslides                         2.2         
packaging                          17.1        
pandas                             0.23.0      
pandocfilters                      1.4.2       
param                              1.9.3       
parso                              0.2.0       
partd                              0.3.8       
path.py                            11.0.1      
pathlib2                           2.3.2       
patsy                              0.5.0       
pbr                                4.1.0       
pep8                               1.7.1       
pexif                              0.15        
pexpect                            4.5.0       
pickleshare                        0.7.4       
Pillow                             5.1.0       
pip                                20.0.2      
pkginfo                            1.4.2       
plotly                             3.10.0      
pluggy                             0.13.1      
ply                                3.11        
portend                            2.3         
prompt-toolkit                     3.0.3       
protobuf                           3.11.3      
psutil                             5.4.5       
ptyprocess                         0.5.2       
py                                 1.5.3       
py-spy                             0.3.3       
py-wsi                             1.1         
pyarrow                            0.13.0      
pycodestyle                        2.4.0       
pycosat                            0.6.3       
pycparser                          2.18        
pycrypto                           2.6.1       
pyct                               0.4.6       
pycurl                             7.43.0.1    
pyflakes                           1.6.0       
Pygments                           2.2.0       
PyHamcrest                         1.9.0       
pyimagej                           0.5.0       
pyjnius                            1.2.1       
pylibczi                           1.1.1       
pylint                             1.8.4       
pymongo                            3.7.0       
pyodbc                             4.0.23      
pyOpenSSL                          18.0.0      
pyparsing                          2.2.0       
PyPDF2                             1.26.0      
PySide2                            5.14.0      
PySocks                            1.6.8       
pytest                             5.3.1       
pytest-arraydiff                   0.2         
pytest-astropy                     0.3.0       
pytest-doctestplus                 0.1.3       
pytest-openfiles                   0.3.0       
pytest-pylint                      0.14.1      
pytest-remotedata                  0.2.1       
python-dateutil                    2.6.1       
pytz                               2018.4      
PyWavelets                         0.5.2       
PyYAML                             3.12        
pyzmq                              17.0.0      
QtAwesome                          0.4.4       
qtconsole                          4.3.1       
QtPy                               1.9.0       
ray                                0.8.4       
redis                              3.5.0       
requests                           2.18.4      
requests-toolbelt                  0.8.0       
retrying                           1.3.3       
roman                              2.0.0       
rope                               0.10.7      
ruamel-yaml                        0.15.35     
s3transfer                         0.1.13      
scikit-build                       0.7.1       
scikit-image                       0.14.2      
scikit-learn                       0.19.1      
scipy                              1.4.1       
scyjava                            0.4.0       
seaborn                            0.8.1       
Send2Trash                         1.5.0       
setuptools                         38.7.0      
setuptools-scm                     2.1.0       
Shapely                            1.6.4.post1 
shiboken2                          5.14.0      
simplegeneric                      0.8.1       
singledispatch                     3.4.0.3     
six                                1.11.0      
slideseg                           1.1         
snowballstemmer                    1.2.1       
sortedcollections                  0.6.1       
sortedcontainers                   1.5.10      
Sphinx                             1.7.4       
sphinxcontrib-websupport           1.0.1       
spyder                             3.2.8       
SQLAlchemy                         1.2.7       
statsmodels                        0.9.0       
stevedore                          1.28.0      
sympy                              1.1.1       
tables                             3.4.3       
TBB                                0.1         
tblib                              1.3.2       
tempora                            1.13        
tensorboard                        1.9.0       
tensorflow                         1.9.0       
termcolor                          1.1.0       
terminado                          0.8.1       
testpath                           0.3.1       
tf-keras-contrib                   2.0.8       
tifffile                           2019.7.26.2 
toolz                              0.9.0       
tornado                            5.0.2       
tqdm                               4.46.0      
traitlets                          4.3.2       
Twisted                            18.7.0      
txaio                              2.10.0      
typing                             3.6.4       
typing-extensions                  3.7.4.2     
umap-learn                         0.3.10      
unicodecsv                         0.14.1      
untangle                           1.1.1       
urllib3                            1.22        
vine                               1.1.4       
vispy                              0.6.4       
wcwidth                            0.1.7       
webencodings                       0.5.1       
websocket-client                   0.48.0      
Werkzeug                           0.14.1      
wheel                              0.31.1      
widgetsnbextension                 3.2.1       
wrapt                              1.10.11     
xarray                             0.13.0      
xlrd                               1.1.0       
XlsxWriter                         1.0.4       
xlwings                            0.11.8      
xlwt                               1.2.0       
xmltodict                          0.12.0      
yarl                               1.4.2       
zict                               0.1.3       
zipp                               0.6.0       
zope.interface                     4.5.0

**Comment by esc** [comment] 2020-05-06 07:13
@rjgiedt thanks for reporting this on the Numba issue tracker. It looks very similar to: https://github.com/numba/llvmlite/issues/587 - However, it appears as though your Numba and llvmlite versions are a few years old. There are two thing to do next: 1) update both `numba` and `llvmlite` and if that doesn't help 2) report back your operating system. Thanks!

**Comment by rjgiedt** [comment] 2020-05-06 12:49
Hi,

I upgraded all packages, numba is now at 0.49.0 and llvmlite is at 0.32.0 and am running on macOS Mojave (10.14.6).  I repeated the process above, just trying to import datashader and still ran into a kernel shutdown.  Thanks so much for the help!

**Comment by esc** [comment] 2020-05-06 13:22
@rjgiedt thanks for looking into this. In order to debug this further, could you perhaps share some more details on your Python version, how you obtained it including Numba and llvmlite and what commands you are running to cause the error? I'd like to get to a point where I can reproduce this error to investigate it further, ideally with a self-contained script, so the more details you can include the higher the chance are of being able to create a reproducer. Thanks!

**Comment by rjgiedt** [comment] 2020-05-06 13:39
Of course, happy to help. 

**Python version**: 3.6.10

**Command to reproduce the error was simply**:  import datashader as ds

I'm running this via Anaconda on a Jupyter Notebook, packages were installed via conda install/ conda update. Again, running python through my terminal also produces an error "Assertion failed: (PassInf && "Expected all immutable passes to be initialized"), function addImmutablePass, file /opt/concourse/worker/volumes/live/636f0d85-60d4-452d-50e9-ca6ab5111e2d/volume/llvmdev_1560805383854/work/lib/IR/LegacyPassManager.cpp, line 849.
Abort trap: 6" 

I'll try to do a fresh install on a different mac machine later today to see if I can independently replicate the error on my end as well and will report back anything I find here!

**Comment by rjgiedt** [comment] 2020-05-08 15:00
Hi,  yes on a separate install I'm getting the same error, unfortunately. Thanks again for checking into this!

**Comment by esc** [comment] 2020-05-11 11:22
@rjgiedt thanks for reporting back, would it be possible to detail how you set up your conda environment and the packages you installed?

**Comment by jlstevens** [comment] 2020-08-10 16:04
Are there any updates on this issue?  @esc have you managed to reproduce this, or do you need more info from @rjgiedt?

**Comment by esc** [comment] 2020-08-10 16:16
@jlstevens thanks for following up, I have not been able to reproduce this yet and am still waiting on additional info.

**Comment by kcpevey** [comment] 2021-01-25 16:38
Closing for now since its not reproducible. Happy to reopen with details on how to reproduce including specific conda env involved.

**Closed by kcpevey** 2021-01-25 16:38 UTC
Labels: bug, needs info
