### ISSUE TITLE
Embed datashade in Flask

### ISSUE THREAD

**Issue by anderl80** [holoviz/datashader#756] opened 2019-06-21 17:00 UTC
How can I embed an interactive datashaded plot (using datashade(hv.Curve ..) and using a gv get_maptiles map in background) in a Flask app?

**Comment by jbednar** [comment] 2019-06-21 18:13
I haven't tried it, but if you use the Bokeh backend with HoloViews, your resulting chart is a Bokeh object.  Bokeh objects can be served in Flask as described in the [Bokeh docs](https://bokeh.pydata.org/en/latest/docs/user_guide/embed.html), and there are [various guides online](https://www.google.com/search?q=bokeh+flask) that might offer additional tips.

**Comment by anderl80** [comment] 2019-06-21 18:48
Using `from bokeh.embed import components` is exactly what I did. But then the datashaded plot is not updated when I zoom into the map.
That's how I create the graph:
```python
tile_opts = dict(width=plot_width, height=plot_height, xaxis=None, yaxis=None, show_grid=False)
map_tiles = gts.CartoLight.opts(style=dict(alpha=1), plot=tile_opts)

lines = hv.Curve(shade_pd[["from_lon", "from_lat", "to_lon", "to_lat"]], ["from_lon", "from_lat"],
                     ["to_lon", "to_lat"])
routes = datashade(lines, x_sampling=2, y_sampling=2, cmap=bgy, x_range=(x1, x2), y_range=(y1, y2), alpha=50)
map_tiles * routes
```
I then try to embed map_tiles * routes in the Flask app, which does only work to a certain content (only a minor rectangle of the data is plotted and the plot is not updated when I zoom like it is in a Jupyter Notebook)

**Comment by jbednar** [comment] 2019-06-21 18:56
Ah.  I've used Flask, but only for separate non-plotting servers, and I haven't tried embedding any dynamic Bokeh plots.  Here it seems like the issue isn't Datashader per se, just any Python-backed Bokeh plot that's not a simple export.  If you can track down such an example, the same approach will probably work for Datashader as well. Depends on how communication channels are set up with Flask; something to follow up on on the Bokeh project.

**Comment by philippjfr** [comment] 2019-06-21 19:01
We'll hopefully add something in the [Panel docs](panel.pyviz.org) about this relatively soon in the deployment section we have planned.

**Comment by anderl80** [comment] 2019-06-22 07:35
Is there a dev branch with intermediate results ?

**Comment by mattpap** [comment] 2019-06-22 08:21
> Depends on how communication channels are set up with Flask; something to follow up on on the Bokeh project.

Here are two, hopefully helpful, Flask embedding examples:

https://github.com/bokeh/bokeh/blob/8f0495bf9e99ff5c0f622d65595893258c73d615/examples/howto/server_embed/flask_embed.py
https://github.com/bokeh/bokeh/blob/8f0495bf9e99ff5c0f622d65595893258c73d615/examples/howto/server_embed/flask_gunicorn_embed.py

**Comment by qtford** [comment] 2019-07-02 20:01
I have almost the exact same use case (datashade over geoviews tiles). I have a working plot that reshades on a zoom in/out using panel serve. I followed the above docs on how to embed in Flask and also lose the reshading on a zoom. Other thoughts on what else I could try?

**Comment by anderl80** [comment] 2019-07-09 15:39
An intermediate update on my work, I switched to Bokeh server standalone (without Flask but launching Bokeh server as library from Tornado). DataShader works. In a second step I have to figure out how to embed this in Flask (I use Cloud Foundry and I have to define the routes accordingly I guess, w.r.t. WebSocket, ..). You can find my gist here: https://gist.github.com/anderl80/f2e7f5d4075704ee84a88ffb2578e30a

@philippjfr Still I'm pretty curious on how Panel could do with Flask! Looking forward for the docs! 👍

**Comment by michaelmcomcast** [comment] 2020-03-01 00:19
Has there been any progress on this? "embed in Flask and lose the reshading on a zoom"

**Comment by sameerCoder** [comment] 2020-05-30 13:25
Hi,
@anderl80 
I am also facing same problem, my panel object is having dynamic property when i plot in jupyter but when i embed my panel / bokeh plot with Flask then plot is coming in webpage but its static in in nature .
No zoom working no dropdown working.
Can you please let me know how i can solve this dynamic issue.
I will really appreciate it.
if u want more detial:- u can visit below link 
a sample similar script i made.
https://stackoverflow.com/questions/62077389/bokeh-embedded-plot-not-acting-dynamic-in-flask-app-with-no-error
thank you.

**Comment by jbednar** [comment] 2020-06-01 19:09
I'm not aware of any progress, no; my own work uses only Tornado, not Flask. But @philippjfr or @mattpap might know of working Flask examples somewhere...

**Comment by mattpap** [comment] 2020-06-01 19:22
The only two Flask embed examples we have in bokeh were already mentioned in  https://github.com/holoviz/datashader/issues/756#issuecomment-504643235.

**Comment by sameerCoder** [comment] 2020-06-05 12:06
@mattpap @jbednar 
Hi,
Can't we change the port number as well as localhost while giving run of embed plot.
I am trying but getting failed.
`from jinja2 import Environment, FileSystemLoader

from tornado.web import RequestHandler

from bokeh.embed import server_document
from bokeh.layouts import column
from bokeh.models import ColumnDataSource, Slider
from bokeh.plotting import figure
from bokeh.server.server import Server
from bokeh.themes import Theme

from bokeh.sampledata.sea_surface_temperature import sea_surface_temperature

env = Environment(loader=FileSystemLoader('templates'))

class IndexHandler(RequestHandler):
    def get(self):
        template = env.get_template('embed.html')
        script = server_document('http://172.16.X.XX:8006/bkapp')
        self.write(template.render(script=script, template="Tornado"))

def modify_doc(doc):
    df = sea_surface_temperature.copy()
    print(df.head())
    source = ColumnDataSource(data=df)
    print("source:",source)
    print("type(source)",type(source))

    plot = figure(x_axis_type='datetime', y_range=(0, 25), y_axis_label='Temperature (Celsius)',
                  title="Sea Surface Temperature at 43.18, -70.43")
    finalplot=plot.line('time', 'temperature', source=source)
    print("type()")

    def callback(attr, old, new):
        if new == 0:
            data = df
        else:
            data = df.rolling('{0}D'.format(new)).mean()
        source.data = ColumnDataSource(data=data).data

    slider = Slider(start=0, end=30, value=0, step=1, title="Smoothing by N Days")
    slider.on_change('value', callback)

    doc.add_root(column(slider, plot))

    doc.theme = Theme(filename="theme.yaml")

# Setting num_procs here means we can't touch the IOLoop before now, we must
# let Server handle that. If you need to explicitly handle IOLoops then you
# will need to use the lower level BaseServer class.
# The `static/` end point is reserved for Bokeh resources, as specified in
# bokeh.server.urls. In order to make your own end point for static resources,
# add the following to the `extra_patterns` argument, replacing `DIR` with the desired directory.
# (r'/DIR/(.*)', StaticFileHandler, {'path': os.path.normpath(os.path.dirname(__file__) + '/DIR')})
server = Server({'/bkapp': modify_doc}, num_procs=1, extra_patterns=[('/', IndexHandler)])
server.start()

if __name__ == '__main__':
    from bokeh.util.browser import view

    print('Opening Tornado app with embedded Bokeh application on http://172.16.X.XX:8006/')

    server.io_loop.add_callback(view, "http://172.16.X.XX:8006/")
server.io_loop.start()`
Running the program by allowing ip and port number.
`python dynamic1.py --address=172.16.X.XX --port=8006
`
**Can u please let me know, how i can run by dynamic1.py at particular ip address origin and particular port with particular url address.
Thank you.**

**Comment by sameerCoder** [comment] 2020-06-12 04:09
Hi,
I will be really greatful & appreciate your help on this.
Any update on how to set my own ip address  and url inplace of http://localhost:5006/ &  'http://localhost:5006/bkapp'.
I am trying to replace localhost with my system ipaddress then also i can't able to plot in webpage. No error showing only blank page when i replace localhost to my system ipaddress.
**Things i want to do is:-
1- change localhost to my own ip address
    For ex:- http://localhost:5006/ to 172.16.X.XX:8000
2- change url to my own url pattern.
    For ex:- 'http://localhost:5006/bkapp' to 172.16.X.XX:8000/test/secondpage/bokehapp**
example code to work link: https://github.com/bokeh/bokeh/blob/8f0495bf9e99ff5c0f622d65595893258c73d615/examples/howto/server_embed/tornado_embed.py
Thank you.

**Comment by ppwadhwa** [comment] 2021-02-08 16:28
Closing: the issues involved here can't be addressed at the datashader repository level.

**Closed by ppwadhwa** 2021-02-08 16:28 UTC
