### ISSUE TITLE
dynspread fails when the y-axis value is constant

### ISSUE THREAD

**Issue by ravimulpuri** [holoviz/datashader#775] opened 2019-08-06 04:01 UTC
When dynspread is used on the data which is constant on the y-axis, ZeroDivisonError occurs.

For example, the following **code works**

```
import pandas.util.testing as tm
import holoviews as hv
from holoviews.operation.datashader import datashade, dynspread

tm.N, tm.K = 150000, 30  # Module-level default rows/columns
df = tm.makeTimeDataFrame(freq='1Min')
df.index.name = 'timestamp'
df.columns = ['pc' + t for t in df.columns]
df['pcB'] = 0
datashade(hv.Scatter(x='pcA', y='pcB', data=df))
```

But the following **code doesnt work** and will fail with ZeroDivisonError error

```
import pandas.util.testing as tm
import holoviews as hv
from holoviews.operation.datashader import datashade, dynspread

tm.N, tm.K = 150000, 30  # Module-level default rows/columns
df = tm.makeTimeDataFrame(freq='1Min')
df.index.name = 'timestamp'
df.columns = ['pc' + t for t in df.columns]
df['pcB'] = 0
dynspread(datashade(hv.Scatter(x='pcA', y='pcB', data=df)))
```

It **fails** even with the `hvplot` option

```
import pandas.util.testing as tm
import holoviews as hv
from holoviews.operation.datashader import datashade, dynspread

tm.N, tm.K = 150000, 30  # Module-level default rows/columns
df = tm.makeTimeDataFrame(freq='1Min')
df.index.name = 'timestamp'
df.columns = ['pc' + t for t in df.columns]
df['pcB'] = 0
df.hvplot.scatter(x='pcA', y='pcB', datashade=True, dynspread=True)
```

**Comment by jbednar** [comment] 2021-05-26 19:26
Thanks! I'm closing this now as I wasn't able to reproduce any problem with the current Datashader and HoloViews versions, and because the behavior is likely to differ when we merge htps://github.com/holoviz/datashader/pull/1001. But if you do have such problems with the upcoming 0.13 release, please reopen or file a new issue!

**Closed by jbednar** 2021-05-26 19:26 UTC
